---
variant: flatcar
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys: ${ssh_keys}

#########################################################################
storage:
  files:
    - path: /etc/systemd/resolved.conf.d/00-default-dns-servers.conf
      mode: 0644
      contents:
        inline: |
          [Resolve]
          DNS=${dns_servers}

    - path: /etc/flatcar/update.conf
      mode: 0644
      contents:
        inline: |
          GROUP=${update_group}
          SERVER=${update_server}
          MACHINE_ALIAS=${hostname}
          REBOOT_STRATEGY=reboot

    - path: /etc/crictl.yaml
      mode: 0644
      contents:
        inline: |
          runtime-endpoint: unix:///run/containerd/containerd.sock

    - path: /opt/bin/reprovision
      mode: 0755
      contents:
        inline: |
          #!/bin/bash
          set -euo pipefail
          touch /usr/share/oem/grub.cfg
          sed -i "/linux_append systemd.machine_id=.*/d" /usr/share/oem/grub.cfg
          echo "set linux_append=\"\$linux_append systemd.machine_id=$(cat /etc/machine-id)\"" >> /usr/share/oem/grub.cfg
          touch /boot/flatcar/first_boot

    - path: /etc/systemd/network/00-eth0.network
      overwrite: true
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          DHCP=yes

          [DHCPv4]
          UseDNS=no

          [DHCPv6]
          UseDNS=no

    - path: /etc/systemd/network/00-eth1.network
      overwrite: true
      contents:
        inline: |
          [Match]
          Name=eth1

          [Network]
          DHCP=yes

          [DHCPv4]
          UseDNS=no

          [DHCPv6]
          UseDNS=no

#########################################################################
systemd:
  units:
    - name: update-engine.service
      enabled: true

    - name: locksmithd.service
      mask: true

    - name: containerd.service
      enabled: true

    - name: docker.socket
      mask: true

    - name: docker.service
      mask: true
